# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - tom-ai

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}
  RESEMBLEAI_TOKEN: ${{ secrets.RESEMBLEAI_TOKEN }}
  RESEMBLEAI_PROJECTID: ${{ secrets.RESEMBLEAI_PROJECTID }}
  RESEMBLEAI_VOICEID: ${{ secrets.RESEMBLEAI_VOICEID }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          exclude: venv/
        
      - name: Create environment file
        run: |
          echo "OPENAI_TOKEN=${OPENAI_TOKEN}" >> .env
          echo "RESEMBLEAI_TOKEN=${RESEMBLEAI_TOKEN}" >> .env
          echo "RESEMBLEAI_PROJECTID=${RESEMBLEAI_PROJECTID}" >> .env
          echo "RESEMBLEAI_VOICEID=${RESEMBLEAI_VOICEID}" >> .env    
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'tom-ai'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6735406C95AF4C2497DD9AF0FF5B95A8 }}
